@Catalog.Public.Api_HostAddress = http://localhost:5169

GET {{Catalog.Public.Api_HostAddress}}/weatherforecast/
Accept: application/json

###


curl -X 'POST' 
'https://localhost:44331/api/Products' 
-H 'accept: application/json' 
-H 'Content-Type: multipart/form-data' 
-F 'StockQuantity=432' 
-F 'Brand=teste' 
-F 'Price=324' 
-F 'Name=test' 
-F 'Description=etset' 
-F 'SKU=432'

curl -X "POST" \
  "https://localhost:44331/api/Products" \
  -H "accept: application/json" \
  -H "Content-Type: multipart/form-data" \
  -F "StockQuantity=432" \
  -F "Brand=teste" \
  -F "Price=324" \
  -F "Name=test" \
  -F "Description=etset" \
  -F "SKU=432"

### Get All Products
GET {{Catalog.Public.Api_HostAddress}}/api/Products
Accept: application/json

###

### Get Product By Id
GET {{Catalog.Public.Api_HostAddress}}/api/Products/{id}
Accept: application/json

###

### Create Product
POST https://localhost:44331/api/Products
Content-Type: multipart/form-data
{
  "Name": "string",
  "Description": "string",
  "CategoriesId": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ],
  "Price": 0,
  "StockQuantity": 0,
  "SKU": "string",
  "Brand": "string",
  "Tags": [
    "string"
  ],
}

###

### Update Product
PUT {{Catalog.Public.Api_HostAddress}}/api/Products/{id}
Content-Type: application/json

{
  "Name": "string",
  "Description": "string",
  "CategoriesId": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ],
  "Price": 0,
  "StockQuantity": 0,
  "SKU": "string",
  "Brand": "string",
  "Tags": [
    "string"
  ],
  "Files": [
    "string"
  ]
}

###

### Delete Product
DELETE {{Catalog.Public.Api_HostAddress}}/api/Products/{id}
Accept: application/json

###

### Get All Categories
GET {{Catalog.Public.Api_HostAddress}}/api/Categories
Accept: application/json

###

### Get Category By Id
GET {{Catalog.Public.Api_HostAddress}}/api/Categories/{id}
Accept: application/json

###

### Create Category
POST {{Catalog.Public.Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "string",
  "Description": "string"
}

###

### Update Category
PUT {{Catalog.Public.Api_HostAddress}}/api/Categories/{id}
Content-Type: application/json

{
  "Name": "string",
  "Description": "string"
}

###

### Delete Category
DELETE {{Catalog.Public.Api_HostAddress}}/api/Categories/{id}
Accept: application/json